enable-magisk-update = true   # set this to false if you do not want to receive updates for the module in magisk app

# add 'enabled = false' for not patching a specific app or remove it from the config
# see https://github.com/j-hc/revanced-magisk-module/blob/main/CONFIG.md for more detailed explanations

# you can use rvmm-config-gen to generate a config

[YouTube]
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
version = "19.11.43"
included-patches = "'Custom branding' 'Change header'"
excluded-patches = "'Restore old video quality menu' 'Playback speed' 'Always repeat' 'Open links externally' 'Custom player overlay opacity' 'Spoof app version' 'Copy video URL'"
